### ISSUE TITLE
Add Jitsi to traefik

### ISSUE THREAD

**Issue by ineiti** [c4dt/traefik-docker#2]
I started installing jitsi to c4dtsrv1, but for some reason traefik doesn't want to mount the `/usr/share/jitsi-meet` directory. Apache complains that it couldn't create the directory, which is strange, as it only creates non-existing directories.

**Comment by cgrigis** [comment]
Thanks to [this issue](https://github.com/linuxserver/docker-tautulli/issues/44) pointing [here](https://github.com/docker-archive/docker-snap/blob/master/README.md#usage), it seems that the mounting problem came with the usage of docker snap :facepalm:, which has limitations on the location of the paths that a container can access.

**Comment by cgrigis** [comment]
To fix the issue for now, I manually copied the contents of the needed mountpoints in subdirectories of `/home/traefik/`; this should be fixed later one by using a non-snap version of docker on c4dtsrv1.
